```{r}
M31 <- matrix(0, nrow = 889, ncol = 8)
for (i in 1:889) {
  for (j in 2:8) {
    M31[i, j] <- as.numeric(data2[i, j])
  }
}

#排除偏差的資料
for (i in 889:1) {
  if ((M31[i, 2] < Q[2]) || (M31[i, 2] > Q[4])) {
    M31 <- M31[-i, ]
  }
}

#命名，方便作業
市值 <- M31[, 2]
資產總額 <- M31[, 3]
負債總額 <- M31[, 4]
稅後淨利率 <- M31[, 5]
保留盈餘 <- M31[, 6]
外資比率 <- M31[, 7]
內部人比率 <- M31[, 8]

資產總額2 <- (資產總額)^2
負債總額2 <- (負債總額)^2
保留盈餘2 <- (保留盈餘)^2
外資比率2 <- (外資比率)^2

#經過多次測試之後找到的比較好的迴歸參數
r31 <- lm(市值 ~ 資產總額 + 負債總額 + 稅後淨利率 + 保留盈餘 + 外資比率 + 內部人比率 + 資產總額2 + 負債總額2 + 保留盈餘2 + 外資比率2 + (資產總額)*(負債總額) + (資產總額)*(內部人比率) + (負債總額)*(內部人比率) + (稅後淨利率)*(外資比率) + (保留盈餘)*(外資比率) + (外資比率)*(內部人比率))
plot(x = 市值, y = r31$fitted.values, xlab = "市值", ylab = "估計值", main = "全部")
abline(b = 1, a = 0, col = "red")
```
## 第二部分，用實際資料測試
```{r}
data3<-read.csv("C:\\Users\\andyw\\OneDrive\\桌面\\課本\\統計軟體實務應用\\data19-21.csv")
M32 <- matrix(0, nrow = 870, ncol = 21)
for (i in 1:870) {
  for (j in 2:22) {
    M32[i, j-1] <- as.numeric(data3[i, j])
  }
}

Q3 <- quantile(M32[, 15])

C <- 870
for (i in 870:1) {
  if ((M32[i, 15] < Q2[2]) || (M32[i, 15] > Q3[4])) {
    M32 <- M32[-i, ]
    C <- C-1
  }
}

市值19 <- M32[, 15]
資產總額19 <- M32[, 16]
負債總額19 <- M32[, 17]
稅後淨利率19 <- M32[, 18]
保留盈餘19 <- M32[, 19]
外資比率19 <- M32[, 20]
內部人比率19 <- M32[, 21]

資產總額192 <- (資產總額19)^2
負債總額192 <- (負債總額19)^2
保留盈餘192 <- (保留盈餘19)^2
外資比率192 <- (外資比率19)^2

r32<-lm(市值19 ~ 資產總額19 + 負債總額19 + 稅後淨利率19 + 保留盈餘19 + 外資比率19 + 內部人比率19 + 資產總額192 + 負債總額192 + 保留盈餘192 + 外資比率192 + (資產總額19)*(負債總額19) + (資產總額19)*(內部人比率19) + (負債總額19)*(內部人比率19) + (稅後淨利率19)*(外資比率19) + (保留盈餘19)*(外資比率19) + (外資比率19)*(內部人比率19))

#4個欄位的順序是19~20有成長、19~20沒成長、19~21有成長、19~21沒有成長
test<-matrix(0, nrow = 1, ncol = 4)

for (i in 1:C) {
  if (r32$fitted.values[i] > M32[i, 15]) {
    if ((M32[i, 8] / M32[i, 15]) > 1) {
      test[1]<-test[1]+1
    }
    if ((M32[i, 8] / M32[i, 15]) <= 1) {
      test[2]<-test[2]+1
    }
    if ((M32[i, 1] / M32[i, 15]) > 1) {
      test[3]<-test[3]+1
    }
    if ((M32[i, 1] / M32[i, 15]) <= 1) {
      test[4]<-test[4]+1
    }
  }
}
```
